[package]
name = "src-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "src"
path = "src/main.rs"

[dependencies]
rayon = "1"
memmap2 = "0.9"
regex = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
